ims/urls.py
from django.contrib import admin
from django.urls import include, path

from ims import views

urlpatterns = [
    path('', views.login_redirect, name="login_redirect"),
    path('philit/', include('registration.urls')),
    path('philit/', include('officers.urls')),
    path('admin/', admin.site.urls),
]

officers/urls.py
from django.urls import path

from . import views

app_name = 'officers'
urlpatterns = [
    path('officer_list', views.OfficerView.as_view(), name='officer'),
    path('add_officer', views.CreateOfficer.as_view(), name='create_officer'),
    path('members', views.MemberView.as_view(), name='members_list'),
]

registration/urls.py
from django.urls import path

from . import views

app_name = 'registration'
urlpatterns = [
    path('home/', views.IndexView.as_view(), name="home"),
    path('registration/', views.RegistrationView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

events/models.py
from django.db import models

# Create your models here.

officers/models.py
import datetime

from django.db import models
from django.utils import timezone
# Create your models here.


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-
    updating ``created`` and ``modified`` fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Officer(TimeStampedModel):

    POSITION = (
        ('pres', 'President'),
        ('vp', 'Vice President'),
        ('sec', 'Secretary'),
        ('tres', 'Treasurer'),
        ('au', 'Auditor'),
        ('pro', 'Peace Relation Officer')
    )
    full_name = models.CharField(max_length=200)
    position = models.CharField(max_length=100, choices=POSITION)
    date_joined = models.DateField("Date joined", default=datetime.datetime.now())

officers/forms.py
from django import forms
from datetime import datetime
from django.contrib.auth.models import User

from .models import Officer
from .choices import POSITION


class OfficerForm(forms.ModelForm):
    full_name = forms.CharField(required=True, help_text='This field is required', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Full name',
        }
    ))

    position = forms.ChoiceField(required=True, help_text='Choose a position', choices=POSITION, widget=forms.Select(
        attrs={
            'class': 'form-control',
        }
    ))

    class Meta:
        model = Officer
        fields = (
            'full_name',
            'position',
        )

        def save(self, commit=True):
            officer = super(OfficerForm, self).save(commit=False)
            officer.full_name = self.cleaned_data['full_name']
            officer.position = self.cleaned_data['position']
            officer.date_joined = self.cleaned_data[datetime.datetime.now()]
            if commit:
                officer.save()
            return officer

events/views.py
from django.shortcuts import render

# Create your views here.

ims/views.py
from django.shortcuts import redirect


def login_redirect(request):
    return redirect('/philit/login')

officers/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView
from django.urls import reverse_lazy

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from . models import Officer
from . forms import OfficerForm

# Create your views here.


class OfficerView(View):
    template_name = 'officers/list_of_officers.html'

    def get(self, request):
        return render(request, self.template_name)


class CreateOfficer(SuccessMessageMixin, FormView):
    template_name = 'officers/create_officer.html'
    form_class = OfficerForm
    success_url = reverse_lazy('officers:officer')
    success_message = "Successfully added an officer to the list."

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class MemberView(SuccessMessageMixin, View):
    template_name = 'officers/members.html'

    def get(self, request):
        return render(request, 'officers/members.html')

officers/templates/officers/create_officer.html
{% extends 'base.html' %}
{% block head %}<title>Add an Officer</title>{% endblock %}
{% block content %}
<div class="content">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Register an Officer</div>
            <div class="panel-body">
              <form class="registration-form" action="{% url 'officers:create_officer' %}" method="post" autocomplete="off">{% csrf_token %}
                {% include 'messages/messages.html' %}
                {% for field in form %}
             <p>
               {{ field }}
               {% if field.help_text %}
                 <small style="color: grey">{{ field.help_text }}</small>
               {% endif %}
               {% for error in field.errors %}
                 <small style="color: red">{{ error }}</small>
               {% endfor %}
             </p>
           {% endfor %}
              <button type="submit" class="btn btn-primary">Add</button>
              </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

officers/templates/officers/inventory_sample.html
{% extends 'ordering/base.html' %}
{% block inventorys_active %}active{% endblock %}
{% block head %}<title>Inventory menu</title>{% endblock %}
{% block body %}
<div class="container-fluid">
  <h1>Inventory Menu</h1>
      <div class="col-sm-4 col-lg-2">
        <div class="thumbnail">
          <div class="caption">
            <img src="" class="img-responsive">
        <h2><a href="#">{{ inventory.product_name }}</a></h2>

        <!-- View Details -->
        <a href="#" class="btn btn-primary btn-sm" role="button">View Details</a>

        <!-- Delete Product -->
        <form action="#" method="post" style="display: inline;">
            {% csrf_token %}
            <input type="hidden" name="inventory_id" value="" />
            <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-trash"></span>
            </button>
        </form>
          </div>
        </div>
      </div>
</div>
      <div class="col-sm-12">
        <br>
        <a href="#">
            <button type="button" class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an officer
          </button>
        </a>
      </div>
    </div>
</div>

{% endblock %}

officers/templates/officers/list_of_officers.html
{% extends 'base.html' %}
{% block head %}<title>List of Officers</title>{% endblock %}
{% block content %}
<div class="content">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Officers Information</div>
            <div class="panel-body">
              {% include 'messages/messages.html' %}
              <div class="container-fluid">
                    <div class="col-sm-4 col-lg-2">
                      <div class="thumbnail">
                        <div class="caption">
                          <img src="" class="img-responsive">
                      <h2><a href="#">  </a></h2>

                      <!-- View Details -->
                      <a href="#" class="btn btn-primary btn-sm" role="button">View Details</a>

                      <!-- Delete Product -->
                      <form action="#" method="post" style="display: inline;">
                          {% csrf_token %}
                          <input type="hidden" name="inventory_id" value="" />
                          <button type="submit" class="btn btn-default btn-sm">
                              <span class="glyphicon glyphicon-trash"></span>
                          </button>
                      </form>
                        </div>
                      </div>
                    </div>
              </div>
                    <div class="col-sm-12">
                      <br>
                      <a href="{% url 'officers:create_officer' %}">
                          <button type="button" class="btn btn-success">
                          <span class="glyphicon glyphicon-plus"></span>&nbsp; Add
                        </button>
                      </a>
                    </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
</div>
{% endblock   %}

officers/templates/officers/members.html
{% extends 'base.html' %}
{% block head %}<title>Members</title>{% endblock %}
{% block content %}
<div class="content">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Members lists</div>
            <div class="panel-body">
                {% include 'messages/messages.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}